/* ============================================================
   unna — dati di contenuto
   Team reale (da ciaounna.com). Eventi inventati ma plausibili
   (Sicilia interna) — da sostituire con dati reali.
   ============================================================ */
window.UNNA = {
  social: {
    instagram: "https://www.instagram.com/unna.city/",
    instagramHandle: "@unna.city",
    email: "unna.city@gmail.com",
  },

  team: [
    {
      id: "miriam",
      foto: "assets/team-miriam.jpg",
      nome: "Miriam Cannella",
      ruolo: "Sustainability Expert",
      bio: "Mantiene la rotta sull'impatto: misura, mette in discussione, non accetta scorciatoie. Per lei la sostenibilità non è un'etichetta ma una pratica quotidiana di cura.",
      parola: "rigenerare",
      tinta: "viola",
      linkedin: "https://www.linkedin.com/in/miriam-cannella/",
    },
    {
      id: "paola",
      foto: "assets/team-paola.jpg",
      nome: "Paola Di Dio",
      ruolo: "Tourism Expert",
      bio: "Progetta itinerari che non trovi sulle guide. Conosce i ritmi lenti dei paesi e li trasforma in momenti che restano.",
      parola: "muovere",
      tinta: "arancio",
      linkedin: "https://www.linkedin.com/in/paola-di-dio-7362a82aa/",
    },
    {
      id: "francesca",
      foto: "assets/team-francesca.jpg",
      nome: "Francesca Diana",
      ruolo: "Product Designer",
      bio: "Mette le mani in pasta e traduce idee in realtà. Permette alle persone di trovare e vivere esperienze di valore in modo intuitivo.",
      parola: "connettere",
      tinta: "viola-300",
      linkedin: "https://www.linkedin.com/in/francesca-diana/",
    },
    {
      id: "serena",
      foto: "assets/team-serena.jpg",
      nome: "Serena Nasino",
      ruolo: "Marketing Expert",
      bio: "Racconta unna senza tradirla. Trova il linguaggio giusto affinché il messaggio arrivi e resti, dentro e fuori la rete.",
      parola: "raccontare",
      tinta: "arancio-2",
      linkedin: "https://www.linkedin.com/in/serenanasino/",
    },
    {
      id: "federica",
      foto: "assets/team-federica.jpg",
      nome: "Federica Cifarelli",
      ruolo: "Inclusivity Expert",
      bio: "Costruisce spazi in cui ci sia spazio per tutti e tutte. Scova barriere invisibili e trasforma l'accessibilità in prerequisito.",
      parola: "includere",
      tinta: "inchiostro",
      linkedin: "https://www.linkedin.com/in/federica-cifarelli-47627412a/",
    },
    {
      id: "gaia",
      foto: "assets/team-gaia.jpg",
      nome: "Gaia Catalano",
      ruolo: "Activation Expert",
      bio: "Rende possibili eventi indimenticabili. Coordina persone, cose, luoghi, tempi e imprevisti affinché tu possa concentrarti ad essere presente e goderti il momento.",
      parola: "animare",
      tinta: "arancio-2",
      linkedin: "",
    },
    {
      id: "eleonora",
      foto: "assets/team-eleonora.jpg",
      nome: "Eleonora Parlascino",
      ruolo: "Territorial Economist",
      bio: "Interpreta i territori attraverso i numeri, ma non si ferma lì. Cerca quelle leve economiche che rendono la rigenerazione concreta e sostenibile.",
      parola: "valorizzare",
      tinta: "viola-300",
      linkedin: "https://www.linkedin.com/in/eleonora-parlascino-2b353234b/",
    },
  ],

  eventi: [
    {
      id: "mani-di-terra",
      dataISO: "2026-09-06",
      titolo: "Mani di Terra: Laboratorio di Argilla",
      sommario: "Un'esperienza collettiva per riscoprire il valore del fare insieme attraverso la modellazione dell'argilla.",
      luogo: "Piazza Armerina",
      provincia: "Enna",
      data: "Settembre 2026",
      dataBreve: "SET",
      tinta: "arancio",
      tags: ["Laboratorio", "Artigianato", "Comunità"],
      descrizione: "Un'esperienza collettiva che invita a riscoprire il valore del fare insieme attraverso la modellazione dell'argilla. Proverai l'emozione di trasformare un cubo di argilla in un oggetto da portare a casa con te. Adatto a persone di tutte le età. Si ripete — puoi venire una volta o tutte le volte che vuoi.",
      programma: [
        { titolo: "Accoglienza e materiali", body: "Presentazione del laboratorio e distribuzione dell'argilla a ogni partecipante." },
        { titolo: "Modellazione libera", body: "Ognuno trasforma il proprio cubo di argilla in un oggetto personale, guidato dai facilitatori." },
        { titolo: "Essiccazione e saluti", body: "L'oggetto viene messo ad asciugare. Puoi tornare a ritirarlo o partecipare di nuovo." },
      ],
      info: [
        { k: "Luogo", v: "Piazza Armerina" },
        { k: "Data", v: "Settembre 2026" },
        { k: "Prenotazione", v: "Su prenotazione" },
        { k: "Età", v: "Adatto a tutte le età" },
        { k: "Gruppo", v: "Piccolo gruppo" },
        { k: "Ripetizioni", v: "Si ripete — puoi venire una o più volte" },
      ],
      contatti: { tel: "", email: "unna.city@gmail.com" },
    },
    {
      id: "visioni-sul-futuro",
      dataISO: "2026-09-13",
      titolo: "Visioni sul Futuro: Docufilm The Cost of Growth",
      sommario: "Proiezione del documentario The Cost of Growth e spazio di confronto aperto sulle grandi sfide del nostro tempo.",
      luogo: "Piazza Armerina / Scicli",
      provincia: "Enna",
      data: "Settembre 2026",
      dataBreve: "SET",
      tinta: "inchiostro",
      tags: ["Documentario", "Sostenibilità", "Confronto"],
      descrizione: "Cosa succede nel nostro mondo? Quali sono gli effetti della crescita economica sui territori, sulle comunità e sull'ambiente? Attraverso la visione del documentario The Cost of Growth esploreremo alcune delle grandi sfide del nostro tempo. Al termine della proiezione ci prenderemo uno spazio di confronto aperto per condividere riflessioni, domande e possibili prospettive per il futuro.",
      programma: [
        { titolo: "Proiezione", body: "Visione del documentario The Cost of Growth." },
        { titolo: "Spazio di confronto", body: "Riflessioni aperte, domande e prospettive condivise con il gruppo." },
      ],
      info: [
        { k: "Prima data", v: "Settembre 2026 — Piazza Armerina" },
        { k: "Seconda data", v: "Settembre 2026 — Scicli" },
        { k: "Ingresso", v: "Gratuito" },
      ],
      contatti: { tel: "", email: "unna.city@gmail.com" },
    },
    {
      id: "un-filo-alla-volta",
      dataISO: "2026-09-20",
      titolo: "Un Filo alla Volta: Laboratorio di Uncinetto",
      sommario: "Tre incontri per imparare l'uncinetto, realizzare la propria borsa e condividere il piacere di creare insieme.",
      luogo: "Piazza Armerina",
      provincia: "Enna",
      data: "Settembre 2026",
      dataBreve: "SET",
      tinta: "arancio-2",
      tags: ["Laboratorio", "Artigianato", "Uncinetto"],
      descrizione: "Un percorso. Tre incontri. Gruppi da 6 persone. Dove creatività, apprendimento e socialità si intrecciano. Ogni partecipante potrà realizzare la propria borsa o il proprio borsello all'uncinetto scegliendo colori, forme e dettagli personali, condividendo il piacere di creare insieme e valorizzando il sapere artigianale.",
      programma: [
        { titolo: "Primo incontro — Le basi", body: "Introduzione all'uncinetto: punti fondamentali e scelta di colori e filati." },
        { titolo: "Secondo incontro — La forma", body: "Si lavora alla struttura della borsa o del borsello, con il supporto della facilitatrice." },
        { titolo: "Terzo incontro — I dettagli e la chiusura", body: "Finiture, dettagli personali e presentazione dei lavori al gruppo." },
      ],
      info: [
        { k: "Luogo", v: "Piazza Armerina" },
        { k: "Data", v: "Settembre 2026" },
        { k: "Incontri", v: "3 incontri" },
        { k: "Gruppo", v: "Max 6 persone" },
        { k: "Prenotazione", v: "Su prenotazione" },
      ],
      contatti: { tel: "", email: "unna.city@gmail.com" },
    },
    {
      id: "muoversi-e-un-atto-di-cura",
      dataISO: "2026-09-27",
      titolo: "Muoversi è un Atto di Cura: Passeggiata al Bosco Bellia",
      sommario: "Una camminata nel bosco trasformata in un gesto concreto di cura per l'ambiente e la comunità.",
      luogo: "Piazza Armerina",
      provincia: "Enna",
      data: "Settembre 2026",
      dataBreve: "SET",
      tinta: "viola-300",
      tags: ["Natura", "Comunità", "Ambiente"],
      descrizione: "L'aria del bosco ci regala una sensazione di benessere. Durante la passeggiata faremo anche la nostra parte: raccoglieremo insieme piccoli rifiuti lungo il percorso, trasformando una semplice camminata in un gesto concreto di cura per l'ambiente e la comunità.",
      programma: [
        { titolo: "Ritrovo e partenza", body: "Ci ritroviamo all'ingresso del Bosco Bellia per iniziare la passeggiata insieme." },
        { titolo: "Camminata e raccolta rifiuti", body: "Percorso nel bosco con sacchetti a disposizione per raccogliere i piccoli rifiuti lungo il cammino." },
        { titolo: "Momento di condivisione", body: "Al termine della camminata uno spazio per condividere riflessioni e sensazioni." },
      ],
      info: [
        { k: "Luogo", v: "Bosco Bellia, Piazza Armerina" },
        { k: "Data", v: "Settembre 2026" },
        { k: "Ingresso", v: "Gratuito" },
        { k: "Cosa portare", v: "Scarpe comode e acqua" },
      ],
      contatti: { tel: "", email: "unna.city@gmail.com" },
    },
  ],
};
